# Generated by Django 4.2.2 on 2023-07-18 19:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_favorites"),
    ]

    operations = [
        migrations.CreateModel(
            name="User_character",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=255, unique=True)),
                ("favorite_vectors", models.JSONField(default=list)),
                ("description", models.TextField()),
            ],
        ),
    ]
