# Generated by Django 4.2.2 on 2023-07-17 13:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stories", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="stories",
            name="language",
            field=models.CharField(default="None", max_length=10),
        ),
    ]
